spring:
  application:
    name: ai-integration

server:
  port: 5644

ai:
  api:
    url: http://localhost:11434/api/chat
    model: gemini-3-flash-preview:cloud
    timeout: 30


#ai:
#  provider: openai
#  api:
#    url: https://api.openai.com/v1/chat/completions
#    model: gpt-4o-mini
#    key: ${OPENAI_API_KEY}
#    timeout: 30